#define BASE_PER_DDRBUS 32
#define BASE_PER_FBUS   16
#define BASE_PER_OBUS   32
#define BASE_PER_WBUS   BASE_PER_FBUS

#define FBUS_PER_DDRBUS (BASE_PER_DDRBUS/BASE_PER_FBUS)
#define FBUS_PER_OBUS   (BASE_PER_OBUS/BASE_PER_FBUS)
#define WBUS_PER_DDRBUS (FBUS_PER_DDRBUS)
#define OBUS_PER_DDRBUS (BASE_PER_DDRBUS/BASE_PER_OBUS)

#define TILE_BUF_SIZE   (120)

#define NUM_FIL_BUF     BASE_PER_OBUS
#define SYS_WID         BASE_PER_FBUS
#define SYS_HT          BASE_PER_OBUS
#define FIL_BUF_SIZE    98

#define NUM_LAYERS      4
#define MAX_MID_SIZE    196

#define FLOAT_NBITS     8
